### ISSUE TITLE
maybe make :EuroZone a synonym for :TARGET

### ISSUE THREAD

**Issue by JeffreySarnoff** [felipenoris/BusinessDays.jl#14]
The only reason not to do this is that other settlement calendars within the EuroZone differ, but that is as with some stock exchanges in a country.  Doing this keeps a consistent presentation (:__Settlement, :PlaceName).  And probably make :TARGET2 a synonym for :TARGET (for accuracy -- they do not overlap).  It is looking good.

**Comment by felipenoris** [comment]
Sure!

**Comment by JeffreySarnoff** [comment]
!
