### ISSUE TITLE
why cache only one calendar?

### ISSUE THREAD

**Issue by JeffreySarnoff** [felipenoris/BusinessDays.jl#15]
Many financial uses of your package will involve a collection of calendars, one for each country with an exchange of interest.  It seems to me that you could bring the throughput that you have with the current distinguished calendar to each of the (really not very many) calendars offered.  A simple way, just to convey the idea, would be to use a dictionary that takes as keys `hash(calendar)` and the values are the respective cache realizations.  Your implementation is sound ..

**Comment by felipenoris** [comment]
I guess it's already there.
Internally caches are stored in `CACHE_DICT` variable.

```julia
const CACHE_DICT = Dict{HolidayCalendar, HolidayCalendarCache}()
```

So this will work as expected:
```julia
BusinessDays.initcache(:Brazil)
BusinessDays.initcache(:TARGET)
```

Please let me know if this is what you expect.

**Comment by JeffreySarnoff** [comment]
yep! (that's some fast coding)

**Comment by felipenoris** [comment]
Great. I´ll close it then.
