### ISSUE TITLE
easy-peasy days(date,date) like bdays

### ISSUE THREAD

**Issue by JeffreySarnoff** [felipenoris/BusinessDays.jl#16]
I know that dates may be subtracted, still this seems a natural export for this package.  And you can be careful about these distinctions:
```julia
using Base.Dates, Base.DateTime

const A_DAY = Day(1)

"""the count of days that are bring 
   min(a_date, b_date) to max(a_date, b_date) 
"""
days_apart(a_date, b_date) = abs(a_date - b_date)

"""the count of days that are between a_date and b_date, excluding a_date and b_date"""
days_inbetween(a_date, b_date) = days_apart(a_date, b_date) - A_DAY

""the number of days that bring a_date into b_date
  a_date = b_date + days_apart(a_date, b_date)
  b_date = a_date + days_apart(b_date, a_date)
"""
days_separating(a_date, b_date) = (a_date - b_date) 

```

**Comment by felipenoris** [comment]
@JeffreySarnoff , thanks for the input!
I would like to keep this package concerned only with business days counting.  Your proposal is about actual days counting. I had to code some of that in `InterestRates.jl` package already, to keep `BusinessDays.jl` with calendars only (see https://github.com/felipenoris/InterestRates.jl/blob/master/src/daycount.jl)
