### ISSUE TITLE
Request: New type for generic calendar

### ISSUE THREAD

**Issue by JockLawrie** [felipenoris/BusinessDays.jl#21]
Hi there,

I have a script that fetches public holidays for Australia from a government website.
The results are stored in a `Set{Date}`.
To use the `BusinessDays` API (which is great) I construct a calendar using the code below.
I repeat this for every Australian state.

```julia
using BusinessDays

struct GenericCalendar
    holidays::Set{Date}
end

BusinessDays.isholiday(cal::GenericCalendar, dt::Date) = in(dt, cal.holidays)

cal = GenericCalendar(holidays)  # holidays is a set of dates fetched from a govt website
```

I use the code snippet above quite a lot, and it's generic provided that the dates are specified rather than derived from rules (such as "1st Monday of August").

Would it be possible to include it in `BusinessDays`?

Cheers,
Jock

**Comment by felipenoris** [comment]
@JockLawrie , hey thanks for the input!
It´s actually a great idea! I´ll work on this.

**Comment by JockLawrie** [comment]
Great! Thanks

**Comment by felipenoris** [comment]
The work is done. I'll tag a new version for this.
Thanks!
