### ISSUE TITLE
Error in using BusinessDays

### ISSUE THREAD

**Issue by vishaluk** [felipenoris/BusinessDays.jl#41]
I am trying to use this package with a dataset which has dates starting from 1960. The error that I get is - Date out of cache bounds. Use initcache function with a wider time spread. How do I specify wide time spread in initcache.

**Comment by felipenoris** [comment]
Please, refer to the docs (readme file): use `BusinessDays.initcache(calendar, [d0], [d1])` as in :

```julia
BusinessDays.initcache(:Brazil, Date(2010, 2, 1), Date(2019, 2, 1))
```

Also, be aware that this package is not targeted at old calendars. So, depending on the holiday calendar you're using, it might not implement the correct holidays for the 60's decade.
