### ISSUE TITLE
eval into closed module BusinessDays

### ISSUE THREAD

**Issue by channelpartnersllc** [felipenoris/BusinessDays.jl#48]
I am working with a local module that depends on BusinessDays and get the below message when importing the module.

```
WARNING: eval into closed module BusinessDays:
:UnitedStates
  ** incremental compilation may be fatally broken for this module **
```

My module is  just a wrapper around some reporting processes that my firm uses frequently. It is pretty much like this:

```
module MyModule

using BusinessDays

BusinessDays.initcache(:UnitedStates)

function foo(x, y)
     bdays(:UnitedStates, x, y)
end

end # module
```

Is this a problem with my code?

**Comment by felipenoris** [comment]
Yes, looking back 5 years ago it was not a good idea to implement `initcache` or `bdays` taking a symbol as input, although incremental compilation was not even a thing back then. I will definitely remove these methods in a future release.

Please, replace your code with the following, and you should be good.

```julia
module MyModule

using BusinessDays

BusinessDays.initcache(BusinessDays.UnitedStates())

function foo(x, y)
     bdays(BusinessDays.UnitedStates(), x, y)
end

end # module
```

**Comment by channelpartnersllc** [comment]
Delightful - that worked great. Many thanks.
