### ISSUE TITLE
Why does the isHoliday method have a bisection

### ISSUE THREAD

**Issue by aviks** [felipenoris/BusinessDays.jl#5]
Hi @felipenoris 

I was looking to add some additional calendars to this package, but looking at the existing code, I had a question. Why does the code in the `isHoliday` function contains a bisection. In other words, why does it have a `if m>=8 ... else ... ` construct?  Is there a performance reason? Thanks!

**Comment by felipenoris** [comment]
Hello @aviks!
The code is there for performance reasons, and only for Brazilian calendar.
I basically wanted to avoid running easter date calculation.
Easter occurs up to April, so Corpus Christi will be up to July in the worst case, which is before August (mm < 8). See `test/easter-min-max.jl`.
This does not affect performance once the calendar cache is created.

**Comment by aviks** [comment]
Ah, thanks, makes sense.
