### ISSUE TITLE
Issue with TARGET calendar

### ISSUE THREAD

**Issue by ASaragga** [felipenoris/BusinessDays.jl#51]
** Forgot that TARGET() calendar also excludes weekends. Closing the issue.

Running the following script 
```
date = Date(2020,12,23)
for i in 1:12
    newdate = date + Day(i)
    println(newdate, " ", BusinessDays.isbday(TARGET(), newdate))
end
```
one gets
```
2020-12-24 true
2020-12-25 false
2020-12-26 false
2020-12-27 false
2020-12-28 true
2020-12-29 true
2020-12-30 true
2020-12-31 true
2021-01-01 false
2021-01-02 false
2021-01-03 false
2021-01-04 true
```

**Comment by felipenoris** [comment]
@ASaragga please note that `isbday` is defined as `!(isweekend(dt) || isholiday(hc, dt))` (https://github.com/JuliaFinance/BusinessDays.jl/blob/34a8bcb655fbd4d63ebda4e3f94da346e036ded8/src/bdays.jl#L28).

Maybe what you're looking for is `isholiday` function (https://github.com/JuliaFinance/BusinessDays.jl/blob/34a8bcb655fbd4d63ebda4e3f94da346e036ded8/src/calendars/target.jl#L9)
