### ISSUE TITLE
US Juneteenth

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/BusinessDays.jl#52]
19/06 is a new national holiday in the US

**Comment by felipenoris** [comment]
https://www.nasdaq.com/articles/will-the-stock-market-close-for-juneteenth-2021-06-17

Looks like NYSE won't be affected on 2021. Maybe next year and beyond.
Federal Holiday in 2021 takes effect immediately, being observed on June 18, given that 19/06 occurs on Saturday.

**Comment by felipenoris** [comment]
https://www.marketwatch.com/story/will-the-stock-and-bond-markets-recognize-juneteenth-with-closures-its-complicated-11623957160

For now, only USSettlement is affected.

**Comment by thedacheng** [comment]
According to https://www.nyse.com/markets/hours-calendars Juneteenth is observed by NYSE markets. Should we update ::USNYSE for this?

**Comment by felipenoris** [comment]
Absolutely!
Thank you!
