### ISSUE TITLE
Create GenericHolidayCalendar where weekends are business days

### ISSUE THREAD

**Issue by ueliwechsler** [felipenoris/BusinessDays.jl#54]
Is there an easy way to create a new `GenericHolidayCalendar` struct - where the weekends are considered business days, unless they are in the `holidays` field of the `GenericHolidayCalendar` - other than dublicate the entire `GenericHolidayCalendar` struct in 
https://github.com/JuliaFinance/BusinessDays.jl/blob/master/src/generic.jl and change the `isbday` function?

**Comment by junder873** [comment]
I don't think you need to copy the structure, just change the `isbday` function:

```julia
function BusinessDays.isbday(hc::GenericHolidayCalendar, dt::Date)::Bool
    if BusinessDays._getcachestate(hc)
        return isbday(BusinessDays._getholidaycalendarcache(hc), dt)
    else
        return !isholiday(hc, dt)
    end
end
```

Then:

```julia
hc = GenericHolidayCalendar([
    Date("2021-12-5"),
    Date("2021-12-8"),
    Date("2021-12-12"),
])

isbday(hc, Date("2021-12-12")) # false

isbday(hc, Date("2021-12-11")) # true
```

**Comment by ueliwechsler** [comment]
Ah yes, you are right. Thanks.

I think it could be a good idea to have an option to define if a `GenericHolidayCalendar` considers weekend days as business days or not. Would you consider adding this functionality to the package if I open a PR?

**Comment by felipenoris** [comment]
The definition of a business day in this package is [a date that is not a weekend or a holiday](https://juliafinance.github.io/BusinessDays.jl/stable/api/#BusinessDays.isbday).

If you need something else, I suggest you implement a separate function for that.

**Comment by ueliwechsler** [comment]
Thanks for the explanation, make sense.
