### ISSUE TITLE
bdays and bdays count give wrong number of business days

### ISSUE THREAD

**Issue by pb866** [felipenoris/BusinessDays.jl#59]
`bdays` and `bdayscount` sometimes give wrong number of business days as demonstrated for August 2022 and the `USSettlement` calendar:

```julia
julia> import BusinessDays as bd

julia> using Dates

julia> bd.initcache(bd.USSettlement())

julia> bd.bdays(bd.USSettlement(), Date(2022, 8), Date(2022, 8, 31))
22 days

julia> bd.bdayscount(bd.USSettlement(), Date(2022, 8), Date(2022, 8, 31))
22

julia> bd.listbdays(bd.USSettlement(), Date(2022, 8), Date(2022, 8, 31))
23-element Vector{Date}:
 2022-08-01
 2022-08-02
 2022-08-03
 2022-08-04
 2022-08-05
 2022-08-08
 2022-08-09
 2022-08-10
 2022-08-11
 2022-08-12
 2022-08-15
 2022-08-16
 2022-08-17
 2022-08-18
 2022-08-19
 2022-08-22
 2022-08-23
 2022-08-24
 2022-08-25
 2022-08-26
 2022-08-29
 2022-08-30
 2022-08-31

julia> length(bd.listbdays(bd.USSettlement(), Date(2022, 8), Date(2022, 8, 31)))
23
```

I am using julia 1.8.2 on an M1 series iMac:

```julia
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by felipenoris** [comment]
This is expected. The way `bdayscount(cal, d1, d2)` is defined accounts for the number of times that "money sleeps" between `d1` and `d2`.  This is usually the desired convention when handling financial contracts.

For instance:

```julia
julia> BusinessDays.bdays(BusinessDays.USSettlement(), Date(2022, 8, 1), Date(2022, 8, 1))
0 days

julia> BusinessDays.bdays(BusinessDays.USSettlement(), Date(2022, 8, 1), Date(2022, 8, 2))
1 day

julia> BusinessDays.listbdays(BusinessDays.USSettlement(), Date(2022, 8, 1), Date(2022, 8, 2))
2-element Vector{Date}:
 2022-08-01
 2022-08-02
```

**Comment by pb866** [comment]
I still find this confusing: Why is Sunday:Monday 0 days and Friday:Saturday 1 day? Somebody not coming from the business world would expect you count the days within a range and that the returned number is equal to the days in listbdays. What difference does it make at the edges of my range, whether a day off was before or after my range? I find the naming of the functions utterly confusing, because this behaviour cannot be anticipated from the function names. At least it should be better explained in the documentation.

**Comment by felipenoris** [comment]
@pb866 thanks for your input!
Please, refer to the docs regarding your question.

https://juliafinance.github.io/BusinessDays.jl/stable/api/#BusinessDays.bdayscount
