### ISSUE TITLE
Veteran's day 2023

### ISSUE THREAD

**Issue by ghazel** [felipenoris/BusinessDays.jl#62]
There have been a number of commits on the issue of Veteran's Day, 2023 ( https://github.com/JuliaFinance/BusinessDays.jl/commit/69da78a0ae5f27ad8f8ba26f0e3b80e136272583 https://github.com/JuliaFinance/BusinessDays.jl/commit/2b32af34a3108d186b4053fc9b25113b26984700 https://github.com/JuliaFinance/BusinessDays.jl/commit/df488339efd302ec1238b56bd27f538a71b546ef ). It falls on Nov 11th 2023, and the code claims it is observed on Nov 10th. That does not reflect the [stated](https://github.com/JuliaFinance/BusinessDays.jl/blob/6da6f8c5fd1c6b3085e96899255c783f71519735/src/calendars/us.jl#L16) [data source](https://www.sifma.org/resources/general/holiday-schedule/) which says there is no recommended Veteran's day in 2023.

https://www.sifma.org/resources/general/holiday-schedule/
<img width="1243" alt="Screenshot 2023-11-08 at 4 20 11 PM" src="https://github.com/JuliaFinance/BusinessDays.jl/assets/31402/81c0cdb6-d8fb-4321-a11c-cbe63cefa6a8">

**Comment by felipenoris** [comment]
@ghazel many thanks!
