### ISSUE TITLE
Checking Canada holidays

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/BusinessDays.jl#8]
@aviks , `Date(2011,1,3)` was really not a business day in Canada?

```
julia> dt = [ Date(2011,1,1), Date(2011,1,2), Date(2011,1,3), Date(2011,1,4) ]
4-element Array{Date,1}:
 2011-01-01
 2011-01-02
 2011-01-03
 2011-01-04

julia> using BusinessDays

julia> isbday(:Canada, dt)
4-element Array{Bool,1}:
 false
 false
 false
  true
```

**Comment by felipenoris** [comment]
Looks like not all holidays that occurs on saturdays are transferred to the next monday.

**Comment by aviks** [comment]
Sorry, have been travelling.. will look at it next week.

**Comment by felipenoris** [comment]
No worries.. I've been also busy. If I can get the time, I'll send a PR with suggestions on this.
